apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: socat-forwarder
  name: socat-forwarder
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "socat-forwarder:latest"
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/ianmiell/socat-forwarder
    type: Git
  strategy:
    type: Docker
