apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2017-09-30T18:24:09Z
  creationTimestamp: null
  generation: 2
  labels:
    app: socat-forwarder
  name: centos
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: centos:7
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/default/centos:7
    generation: 2
    importPolicy: {}
    name: "7"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
